#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using HKOWebMVC4;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HKOWebViews/Studenti/StudentiKompetencije.cshtml")]
    public partial class _Views_HKOWebViews_Studenti_StudentiKompetencije_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<HKOWebMVC4.KolegijKompetencije_Result>>
    {
        public _Views_HKOWebViews_Studenti_StudentiKompetencije_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h5>");

            
            #line 3 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
Write(Html.MvcSiteMap().SiteMapPath());

            
            #line default
            #line hidden
WriteLiteral(" > Kompetencije</h5>\r\n\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(" id=\"studentKompetencije\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
           Write(Html.DisplayNameFor(model => model.Kompetencija));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 14 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
               Write(Html.DisplayFor(modelItem => item.Kompetencija));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 21 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<a");

WriteAttribute("href", Tuple.Create(" href=", 582), Tuple.Create("", 601)
            
            #line 25 "..\..\Views\HKOWebViews\Studenti\StudentiKompetencije.cshtml"
, Tuple.Create(Tuple.Create("", 588), Tuple.Create<System.Object, System.Int32>(ViewBag.back
            
            #line default
            #line hidden
, 588), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Povratak</a>");

        }
    }
}
#pragma warning restore 1591
