//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKOWebMVC4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HKOPodaci : DbContext
    {
        public HKOPodaci()
            : base("name=HKOPodaci")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<KolegijSkupIshodaUcenja_Result> KolegijSkupIshodaUcenja(Nullable<int> kolegijID)
        {
            var kolegijIDParameter = kolegijID.HasValue ?
                new ObjectParameter("KolegijID", kolegijID) :
                new ObjectParameter("KolegijID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KolegijSkupIshodaUcenja_Result>("KolegijSkupIshodaUcenja", kolegijIDParameter);
        }
    
        public virtual ObjectResult<StudijskiProgramIzborniKolegiji_Result> StudijskiProgramIzborniKolegiji(Nullable<int> studijskiProgramID)
        {
            var studijskiProgramIDParameter = studijskiProgramID.HasValue ?
                new ObjectParameter("StudijskiProgramID", studijskiProgramID) :
                new ObjectParameter("StudijskiProgramID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgramIzborniKolegiji_Result>("StudijskiProgramIzborniKolegiji", studijskiProgramIDParameter);
        }
    
        public virtual ObjectResult<StudijskiProgramObavezniKolegiji_Result> StudijskiProgramObavezniKolegiji(Nullable<int> studijskiProgramID)
        {
            var studijskiProgramIDParameter = studijskiProgramID.HasValue ?
                new ObjectParameter("StudijskiProgramID", studijskiProgramID) :
                new ObjectParameter("StudijskiProgramID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgramObavezniKolegiji_Result>("StudijskiProgramObavezniKolegiji", studijskiProgramIDParameter);
        }
    
        public virtual ObjectResult<ZanimanjeKljucniPoslovi_Result> ZanimanjeKljucniPoslovi(Nullable<int> zanimanjeID)
        {
            var zanimanjeIDParameter = zanimanjeID.HasValue ?
                new ObjectParameter("ZanimanjeID", zanimanjeID) :
                new ObjectParameter("ZanimanjeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZanimanjeKljucniPoslovi_Result>("ZanimanjeKljucniPoslovi", zanimanjeIDParameter);
        }
    
        public virtual ObjectResult<ZanimanjeKompetencije_Result> ZanimanjeKompetencije(Nullable<int> zanimanjeID)
        {
            var zanimanjeIDParameter = zanimanjeID.HasValue ?
                new ObjectParameter("ZanimanjeID", zanimanjeID) :
                new ObjectParameter("ZanimanjeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZanimanjeKompetencije_Result>("ZanimanjeKompetencije", zanimanjeIDParameter);
        }
    
        public virtual ObjectResult<string> ZanimanjeNaziv(Nullable<int> zanimanjeID)
        {
            var zanimanjeIDParameter = zanimanjeID.HasValue ?
                new ObjectParameter("ZanimanjeID", zanimanjeID) :
                new ObjectParameter("ZanimanjeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ZanimanjeNaziv", zanimanjeIDParameter);
        }
    
        public virtual ObjectResult<ZanimanjePreporuceniIzborniKolegiji_Result> ZanimanjePreporuceniIzborniKolegiji(Nullable<int> zanimanjeID)
        {
            var zanimanjeIDParameter = zanimanjeID.HasValue ?
                new ObjectParameter("ZanimanjeID", zanimanjeID) :
                new ObjectParameter("ZanimanjeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZanimanjePreporuceniIzborniKolegiji_Result>("ZanimanjePreporuceniIzborniKolegiji", zanimanjeIDParameter);
        }
    
        public virtual ObjectResult<ZanimanjeRadnaMjesta_Result> ZanimanjeRadnaMjesta(Nullable<int> zanimanjeID)
        {
            var zanimanjeIDParameter = zanimanjeID.HasValue ?
                new ObjectParameter("ZanimanjeID", zanimanjeID) :
                new ObjectParameter("ZanimanjeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZanimanjeRadnaMjesta_Result>("ZanimanjeRadnaMjesta", zanimanjeIDParameter);
        }
    
        public virtual ObjectResult<ZanimanjeStudiji_Result> ZanimanjeStudiji()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ZanimanjeStudiji_Result>("ZanimanjeStudiji");
        }
    
        public virtual ObjectResult<StudijskiProgrami_Result> StudijskiProgrami()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgrami_Result>("StudijskiProgrami");
        }
    
        public virtual ObjectResult<StudijskiProgramKljucniPoslovi_Result> StudijskiProgramKljucniPoslovi(Nullable<int> studijskiProgramID)
        {
            var studijskiProgramIDParameter = studijskiProgramID.HasValue ?
                new ObjectParameter("StudijskiProgramID", studijskiProgramID) :
                new ObjectParameter("StudijskiProgramID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgramKljucniPoslovi_Result>("StudijskiProgramKljucniPoslovi", studijskiProgramIDParameter);
        }
    
        public virtual ObjectResult<StudijskiProgramKompetencije_Result> StudijskiProgramKompetencije(Nullable<int> studijskiProgramID)
        {
            var studijskiProgramIDParameter = studijskiProgramID.HasValue ?
                new ObjectParameter("StudijskiProgramID", studijskiProgramID) :
                new ObjectParameter("StudijskiProgramID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgramKompetencije_Result>("StudijskiProgramKompetencije", studijskiProgramIDParameter);
        }
    
        public virtual ObjectResult<StudijskiProgramRadnaMjesta_Result> StudijskiProgramRadnaMjesta(Nullable<int> studijskiProgramID)
        {
            var studijskiProgramIDParameter = studijskiProgramID.HasValue ?
                new ObjectParameter("StudijskiProgramID", studijskiProgramID) :
                new ObjectParameter("StudijskiProgramID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudijskiProgramRadnaMjesta_Result>("StudijskiProgramRadnaMjesta", studijskiProgramIDParameter);
        }
    
        public virtual ObjectResult<KolegijKompetencije_Result> KolegijKompetencije(string kolegijISVUSifra)
        {
            var kolegijISVUSifraParameter = kolegijISVUSifra != null ?
                new ObjectParameter("KolegijISVUSifra", kolegijISVUSifra) :
                new ObjectParameter("KolegijISVUSifra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KolegijKompetencije_Result>("KolegijKompetencije", kolegijISVUSifraParameter);
        }
    }
}
